---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testcrds.hashicorp.com
  labels:
    app: test
spec:
  conversion:
    strategy: None
  group: hashicorp.com
  names:
    kind: TestCrd
    listKind: TestCrdList
    plural: testcrds
    singular: testcrd
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            data:
              type: string
