name: "acceptance tests"
on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev
jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: engineerd/setup-kind@v0.3.0
    - name: Acceptance Tests
      run: |
        make testacc 
