name: Upload Release Binaries
on:
  push:
    tags:
    - [0-9]+.[0-9]+.[0-9]+
jobs:
  build:
    name: Upload Release Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project 
        run: |
          go get -u github.com/mitchellh/gox
          bash scripts/build_release_binaries.sh ${{ github.ref }}
      - name: Create release
        run: |
          set -x
          assets=()
          for asset in ./release-bin/*.zip; do
            assets+=("-a" "$asset")
          done
          hub release create "${assets[@]}" -m "${{ github.ref }}" "${{ github.ref }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}