name: Upload Release Binaries
on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    name: Upload Release Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Install gox
        run: |
          go get -u github.com/mitchellh/gox
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build binaries
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          bash scripts/build_release_binaries.sh ${GITHUB_REF/refs\/tags\//}
      - name: Release binaries
        run: |
          set -x
          assets=()
          for asset in ./release-bin/*.zip; do
            assets+=("-a" "$asset")
          done
          hub release create "${assets[@]}" -m "${GITHUB_REF/refs\/tags\//}" "${GITHUB_REF/refs\/tags\//}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
