name: Tag nightly build

on:
  schedule:
  - cron: 0 0 * * *

jobs:
  tag_nightly:
    name: Tag master with nightly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.NIGHTLY_BUILD_TOKEN }}
    - name: Tag
      run: | 
        git tag nightly$(date +"%Y%m%d")
    - uses: ad-m/github-push-action@master
      with: 
        tags: true
        github_token: ${{ secrets.NIGHTLY_BUILD_TOKEN }}
